### ISSUE TITLE
Test suite writes to the live Supabase; 3 tests fail on `develop`

### ISSUE THREAD

**Issue by chrooks** [chrooks/Cornerstone#116]
## What's wrong

Two related problems, both found while working #113.

### 1. The test suite writes to the live database

Running `pytest` inserted real `threshold_edit` audit rows into `pipeline_runs` on the live Supabase project (three landed during a single session on 2026-07-14, at 14:24:00, 14:24:11, 14:24:40).

The calibration tests exercise the `PUT /skills/thresholds/<skill>?force=true` path, which calls `record_force_audit()` — and nothing is mocked, so the write goes through to the real project. `draft_skill_thresholds` was not clobbered this time (verified: 22 rows, no junk skills), but the same code path *upserts thresholds* — a test that upserted under a real skill name would silently overwrite calibration data.

A test run must never mutate the live project.

### 2. Three tests already fail on `develop`

Verified against a clean tree (stash-checked), so this is pre-existing rot, not a regression:

| test | failure |
|---|---|
| `test_calibration_save_api.py::test_save_threshold_edit_accepts_known_skill` | `invalid input syntax for type uuid: "draft-uuid"` — passes a literal string to real Postgres |
| `test_threshold_edit_params.py::test_save_threshold_edit_uses_threshold_edit_params` | same `"draft-uuid"` failure |
| `test_compositing_and_notability.py::TestSkillSetSizes::test_steady_hand_in_taxonomy_and_legend_prompt` | `_build_legend_prompt() missing 1 required positional argument: 'skills'` — stale signature |

The first two are the same root cause as (1): they hit real Supabase instead of a fake. 202 tests pass.

## Acceptance criteria

- [ ] No test run mutates the live Supabase project — Supabase is faked/mocked at the client Seam, or tests are pointed at a disposable local project
- [ ] The two `"draft-uuid"` tests pass without touching a real database
- [ ] `_build_legend_prompt()` call site updated to the current signature
- [ ] Full suite green on `develop`

## Notes

The `threshold_edit` audit rows already written to `pipeline_runs` are harmless (`rows_processed=0`, no staged results) — no cleanup strictly required, but worth a look if the table is ever used for reporting.

**Comment by chrooks** [comment]
## A 5th test also fails on `develop` — the perf budget

Found while working #114. Adding it here since it's the same family (a red test on `develop` that nobody is tracking):

```
tests/test_cohesion_engine/test_acceptance.py::test_full_nine_player_roster_evaluates_126_lineups_under_100ms
```

It asserts a 9-player roster (126 lineups) evaluates in under 100ms. Measured on a clean `develop` tree, five runs:

    164.9ms  166.1ms  169.1ms  187.4ms  167.6ms

Never passes. It is ~65-85% over its own budget.

Not caused by #114 — verified by stashing. In fact #114 made it slightly *faster* (161ms), because `_percentile_normalize` now walks the already-sorted distribution with `bisect` instead of calling `sorted()` and doing two full O(n) scans on every one of the 126 x 14 calls.

**Decide which is wrong: the budget or the engine.** Either the 100ms target was aspirational and should be re-baselined against reality, or roster evaluation has a real performance problem worth profiling. Right now the test just sits red and teaches everyone to ignore a failing suite.

**Comment by chrooks** [comment]
Launch-safety half landed in db56f09: conftest blanks the Supabase credentials, so no test run can reach a real database (opt in with CORNERSTONE_LIVE_DB_TESTS=1, which still refuses *.supabase.co). backend/.env now points at the hestia dev stack; the prod values are backed up outside the repo. Proof: dev pipeline_runs and draft_skill_thresholds counts identical before and after a full pytest run. Still open: the fake at the client Seam, the 3 red tests, and the 26 other tests that need a real DB (29 fail, identical on clean develop).
